import LoginPage from "../pages/Login";
import SignupPage from "../pages/SignupPage";
import Home from "../pages/Home";
import CreateProduct from "../pages/createProduct";
import MyProducts from "../pages/myProduct";
import Cart from "../pages/Cart";
import ProductDetails from "../pages/ProductDetails";
import Profile from "../pages/Profile";
import CreateAddress from "../pages/createAddress";
import SelectAddress from "../pages/SelectAddress";
import OrderConfirmation from "../pages/OrderConfirmation";
import MyOrdersPage from "../pages/MyOrdersPage";
export {LoginPage,SignupPage,Home,CreateProduct,MyProducts,Cart,ProductDetails,Profile,CreateAddress,SelectAddress,OrderConfirmation,MyOrdersPage};